# Import from numpy

In [3]:
import numpy as np
import torch

In [4]:
a = np.array([2, 3, 3])

In [5]:
torch.from_numpy(a)

tensor([2, 3, 3], dtype=torch.int32)

In [6]:
a = np.ones([2, 3])

In [7]:
# 从Numpy导入的float其实是Double类型
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

# Import from List

In [8]:
torch.tensor([2., 3.2])

tensor([2.0000, 3.2000])

In [9]:
torch.FloatTensor([2., 3.2])

tensor([2.0000, 3.2000])

In [10]:
torch.tensor([[2., 3.2], [1., 22.3]])

tensor([[ 2.0000,  3.2000],
        [ 1.0000, 22.3000]])

# uninitialized
未初始化  
未初始化的数据可能会非常大或者非常小  
未初始化的tensor一定要跟写入的数据的后续步骤  
增强学习一般使用double，其他一般使用float

In [11]:
torch.empty(1)

tensor([0.])

In [12]:
torch.Tensor(2, 3)

tensor([[6.3058e-44, 6.7262e-44, 7.8473e-44],
        [6.3058e-44, 6.7262e-44, 7.1466e-44]])

In [13]:
torch.IntTensor(2, 3)

tensor([[58, 49, 53],
        [46, 52, 49]], dtype=torch.int32)

In [14]:
torch.FloatTensor(2, 3)

tensor([[8.1275e-44, 7.2868e-44, 7.8473e-44],
        [6.4460e-44, 6.8664e-44, 7.4269e-44]])

# set default type

In [15]:
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

In [16]:
torch.set_default_tensor_type(torch.DoubleTensor)

In [17]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

# rand/rand_like,randint
rand：随机产生0-1之间的数值，不包括1  
均匀采样0-10的tensor要用10*torch.rand(d1,d2),randint只能采样整数

In [18]:
torch.rand(3, 3)

tensor([[0.0568, 0.1098, 0.9130],
        [0.7148, 0.2615, 0.3170],
        [0.6220, 0.5800, 0.9449]])

In [19]:
a = torch.rand(3, 3)

In [20]:
torch.rand_like(a)

tensor([[0.4429, 0.6331, 0.2764],
        [0.5655, 0.0608, 0.3135],
        [0.6817, 0.2628, 0.9654]])

In [21]:
torch.randint(1, 10, [3, 3])

tensor([[7, 5, 5],
        [5, 4, 2],
        [3, 4, 9]])

In [22]:
# 正太分布
torch.randn(3, 3)

tensor([[ 0.7793, -0.5691, -0.1428],
        [-0.7544,  1.1545,  0.3420],
        [ 0.5243, -0.7547,  0.9933]])

In [24]:
torch.normal(mean=torch.full([10], 0.), std=torch.arange(1, 0, -0.1))

tensor([ 1.0011,  0.3570,  0.4750,  0.2804,  0.1210, -0.2476,  0.5273,  0.0241,
         0.2053, -0.0353])

In [25]:
torch.normal(mean=torch.full([10], 0.), std=torch.arange(1, 0, -0.1))

tensor([-0.3790, -0.4832, -0.6250,  1.5107,  0.3865,  0.1992, -0.1453,  0.1234,
        -0.1300, -0.0427])

# full

In [26]:
torch.full([2, 3], 7)

tensor([[7, 7, 7],
        [7, 7, 7]])

In [27]:
torch.full([], 7)

tensor(7)

In [28]:
torch.full([1], 7)

tensor([7])

# arange/range

In [29]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [33]:
torch.range(0, 10)

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_20684\1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# linspace/logspace

In [34]:
# linspace等分切
torch.linspace(0, 10, steps=4)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [35]:
torch.linspace(0, 10, steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [36]:
torch.linspace(0, 10, steps=11)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [37]:
torch.logspace(0, -1, steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [38]:
torch.logspace(0, 1, steps=10)

tensor([ 1.0000,  1.2915,  1.6681,  2.1544,  2.7826,  3.5938,  4.6416,  5.9948,
         7.7426, 10.0000])

# Ones/zeros/eye

In [39]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [40]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [41]:
torch.eye(3, 4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [42]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [44]:
a = torch.zeros(3, 3)

In [45]:
torch.ones_like(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# randperm
随机打散  
random.shuffle

In [46]:
# 参数为随机种子
torch.randperm(10)

tensor([2, 3, 4, 8, 5, 0, 9, 6, 1, 7])

In [47]:
a = torch.rand(2, 3)

In [48]:
b = torch.rand(2, 2)

In [49]:
idx = torch.randperm(2)

In [50]:
idx

tensor([1, 0])

In [52]:
a[idx]

tensor([[0.7586, 0.7872, 0.5442],
        [0.4398, 0.2159, 0.8101]])

In [53]:
b[idx]

tensor([[0.1201, 0.4190],
        [0.5656, 0.7552]])

In [54]:
a, b

(tensor([[0.4398, 0.2159, 0.8101],
         [0.7586, 0.7872, 0.5442]]),
 tensor([[0.5656, 0.7552],
         [0.1201, 0.4190]]))