In [4]:
import torch
from torch.nn import functional as F

In [2]:
logits = torch.rand(4, 10)

In [6]:
pred = F.softmax(logits, dim=1)
pred.shape

torch.Size([4, 10])

In [7]:
pred_label = pred.argmax(dim=1)
pred_label

tensor([9, 8, 1, 5])

In [8]:
logits.argmax(dim=1)

tensor([9, 8, 1, 5])

In [11]:
label = torch.tensor([9, 3, 2, 4])
correct = torch.eq(pred_label, label)
correct

tensor([ True, False, False, False])

In [12]:
correct.sum().float().item()/4

0.25