>在输入较小或较大时，sigmoid趋于0或1无法得到更新，所以希望将输入控制在有效的范围内
>不同类型的输入，因为取值范围的不同会导致取值范围大的更新快，取值范围小的更新慢

In [ ]:
normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])

- batch normalization是每个特征上的均值
- layer normalization是每个数据上的均值

In [1]:
import torch
from torch import nn

In [3]:
x = torch.randn(100, 16) + 0.5
layer = torch.nn.BatchNorm1d(16)
layer.running_mean,layer.running_var

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [4]:
out = layer(x)

layer.running_mean, layer.running_var

(tensor([0.0558, 0.0603, 0.0591, 0.0404, 0.0568, 0.0465, 0.0520, 0.0662, 0.0372,
         0.0442, 0.0334, 0.0563, 0.0449, 0.0745, 0.0413, 0.0307]),
 tensor([0.9871, 0.9840, 1.0060, 1.0051, 1.0027, 1.0056, 1.0212, 1.0041, 1.0025,
         0.9997, 0.9811, 1.0144, 0.9893, 1.0158, 1.0090, 0.9848]))

In [5]:
x = torch.randn(100, 16) + 0.5
layer = torch.nn.BatchNorm1d(16)
for i in range(100):
    out = layer(x)
layer.running_mean, layer.running_var

(tensor([0.6107, 0.5618, 0.5460, 0.5654, 0.7070, 0.6067, 0.4169, 0.5533, 0.5466,
         0.4553, 0.4448, 0.5218, 0.4281, 0.5514, 0.4696, 0.3007]),
 tensor([0.8532, 0.9968, 0.9732, 1.0582, 0.9644, 1.0080, 1.1559, 1.1453, 0.9836,
         0.8804, 0.7287, 0.9900, 1.0344, 0.9313, 0.9879, 0.9415]))

# nn.BatchNorm2d

In [ ]:
"""
x.shape

layer = nn.BatchNorm2d(16)

out = layer(x)

layer.weight

layer.weight.shape

layer.bias.shape

vars(layer)  # Class variables 各类参数
"""

In [ ]:
# test
layer.eval()
BatchNorm1d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

out = layer(x)