# autograd.grad
pytorch自动求导  
torch.autograd.grad(loss, [w1,w2,...])  
loss.backward

In [7]:
import torch
from torch.nn import functional as F

In [3]:
x = torch.ones(1)

In [18]:
w = torch.full([1], 2, dtype=torch.float32)
# w = torch.tensor([1], requiregrid=True)

In [10]:
mse = F.mse_loss(torch.ones(1), x*w)
mse

tensor(1.)

In [11]:
# 此处报错是因为没有设置w是否需要梯度信息
torch.autograd.grad(mse, [w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [19]:
# 设置w需要梯度信息
w.requires_grad_()

tensor([2.], requires_grad=True)

In [20]:
# pytorch是动态图，此处报错是因为动态图未更新
torch.autograd.grad(mse, [w])

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [21]:
mse = F.mse_loss(torch.ones(1), x*w)

In [22]:
# 梯度计算
torch.autograd.grad(mse, [w])

(tensor([2.]),)

# loss.backward

In [23]:
x = torch.ones(1)

In [30]:
w = torch.full([1], 2, dtype=torch.float32)

In [31]:
mse = F.mse_loss(torch.ones(1), x*w)
mse

tensor(1.)

In [32]:
w.requires_grad_()

tensor([2.], requires_grad=True)

In [33]:
mse = F.mse_loss(torch.ones(1), x*w)

In [34]:
mse.backward()

In [35]:
w.grad

tensor([2.])

# Softmax

In [40]:
a = torch.rand(3)

In [41]:
a.requires_grad_()

tensor([0.9481, 0.0797, 0.6490], requires_grad=True)

In [42]:
p = F.softmax(a, dim=0)

In [43]:
p.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [44]:
p = F.softmax(a, dim=0)

In [45]:
torch.autograd.grad(p[1], [a], retain_graph=True)

(tensor([-0.0898,  0.1565, -0.0666]),)

In [46]:
torch.autograd.grad(p[2], [a])

(tensor([-0.1588, -0.0666,  0.2254]),)