# Type check

In [1]:
import torch

In [2]:
# 随机初始化（均值为0，方差为1）2行3列的矩阵
a = torch.randn(2, 3)  

In [3]:
a.type()

'torch.FloatTensor'

In [4]:
type(a)

torch.Tensor

In [5]:
isinstance(a, torch.FloatTensor)

True

In [7]:
data = torch.randn(2, 3)

In [8]:
isinstance(data, torch.cuda.DoubleTensor)

False

In [11]:
data = data.cuda()

In [12]:
isinstance(data, torch.cuda.DoubleTensor)

False

# Dimension 0 / rank 0

In [16]:
torch.tensor(1.)

tensor(1.)

In [17]:
torch.tensor(1.3)

tensor(1.3000)

In [18]:
a = torch.tensor(2.2)

In [19]:
a.shape

torch.Size([])

In [20]:
len(a.shape)

0

In [21]:
a.size()

torch.Size([])

# Dimension 1 / rank 1

In [22]:
torch.tensor([1.1])

tensor([1.1000])

In [23]:
torch.tensor([1.1, 2.2])

tensor([1.1000, 2.2000])

In [24]:
torch.FloatTensor(1)

tensor([9.1477e-41])

In [25]:
torch.FloatTensor(2)

tensor([0., 0.])

In [27]:
import numpy as np
data = np.ones(2)

In [28]:
torch.from_numpy(data)

tensor([1., 1.], dtype=torch.float64)

In [29]:
a = torch.ones(2)

In [30]:
a.shape

torch.Size([2])

# Dimension 2

In [31]:
a = torch.randn(2, 3)

In [32]:
a

tensor([[ 0.7305, -0.8286,  0.2773],
        [-0.2969,  1.4615, -0.6502]])

In [33]:
a.shape

torch.Size([2, 3])

In [37]:
a.size(0)

2

In [35]:
a.size(1)

3

In [36]:
a.shape[1]

3

# Dimension 3

In [38]:
a = torch.rand(1, 2, 3)

In [39]:
a

tensor([[[0.2832, 0.1184, 0.7250],
         [0.9871, 0.8413, 0.1273]]])

In [40]:
a.shape

torch.Size([1, 2, 3])

In [42]:
torch.Size([1, 2, 3])

torch.Size([1, 2, 3])

In [43]:
a[0]

tensor([[0.2832, 0.1184, 0.7250],
        [0.9871, 0.8413, 0.1273]])

In [44]:
list(a.shape)

[1, 2, 3]

# Dimension 4

In [45]:
a = torch.rand(2, 3, 28, 28)

In [46]:
a

tensor([[[[0.3697, 0.4240, 0.0287,  ..., 0.8275, 0.9285, 0.8505],
          [0.4735, 0.4785, 0.6491,  ..., 0.0370, 0.1449, 0.2869],
          [0.5017, 0.4399, 0.1959,  ..., 0.2237, 0.6436, 0.6750],
          ...,
          [0.9876, 0.8678, 0.9277,  ..., 0.1909, 0.4314, 0.5909],
          [0.1742, 0.2651, 0.2144,  ..., 0.4131, 0.7213, 0.4424],
          [0.6409, 0.1116, 0.5290,  ..., 0.7951, 0.9067, 0.6063]],

         [[0.5293, 0.8686, 0.4746,  ..., 0.3845, 0.4095, 0.2152],
          [0.6179, 0.6163, 0.4669,  ..., 0.1857, 0.8742, 0.6618],
          [0.5006, 0.4827, 0.9334,  ..., 0.6438, 0.6809, 0.0119],
          ...,
          [0.8554, 0.5653, 0.6034,  ..., 0.3098, 0.8464, 0.4885],
          [0.8339, 0.5263, 0.7784,  ..., 0.6605, 0.3368, 0.1729],
          [0.1880, 0.7296, 0.6450,  ..., 0.2094, 0.8823, 0.5529]],

         [[0.3545, 0.5923, 0.4584,  ..., 0.4581, 0.9968, 0.9980],
          [0.5233, 0.2550, 0.3787,  ..., 0.7997, 0.1876, 0.4567],
          [0.3742, 0.4568, 0.3832,  ..., 0

In [47]:
a.shape

torch.Size([2, 3, 28, 28])

# Mixed

In [48]:
a.shape

torch.Size([2, 3, 28, 28])

In [49]:
# tensor占用内存的数量
a.numel()

4704

In [50]:
# 维度
a.dim()

4

In [51]:
a = torch.tensor(1)

In [52]:
a.dim()

0