# Tensor advanced operation

In [1]:
import torch

## where

In [7]:
cond = torch.randn([2, 2])
cond

tensor([[ 1.2833,  1.0058],
        [-2.4641, -0.6243]])

In [8]:
a = torch.zeros([2, 2])
a

tensor([[0., 0.],
        [0., 0.]])

In [9]:
b = torch.ones([2, 2])
b

tensor([[1., 1.],
        [1., 1.]])

In [10]:
torch.where(cond>0.5, a, b)

tensor([[0., 0.],
        [1., 1.]])

## gather
收集

In [6]:
prob = torch.randn(4, 10)
prob

tensor([[-0.9659,  0.2296, -0.8496, -0.4277,  0.4460,  2.1055, -1.0179, -1.4176,
         -2.0383, -0.3947],
        [ 0.6768, -0.5820, -0.8162, -0.9943,  1.1446, -1.1688,  1.9301, -1.6577,
         -1.6047,  1.4062],
        [-0.6329,  1.1607, -0.8022,  1.0206, -0.4642,  0.8757, -0.4628,  0.8437,
         -1.2622,  0.2094],
        [ 1.6428,  0.7913, -1.1666, -1.6498,  0.4509,  0.2161,  0.6752, -0.6746,
         -0.8898,  0.7637]])

In [12]:
idx = prob.topk(dim=1, k=3)
idx

torch.return_types.topk(
values=tensor([[2.1055, 0.4460, 0.2296],
        [1.9301, 1.4062, 1.1446],
        [1.1607, 1.0206, 0.8757],
        [1.6428, 0.7913, 0.7637]]),
indices=tensor([[5, 4, 1],
        [6, 9, 4],
        [1, 3, 5],
        [0, 1, 9]]))

In [13]:
idx = idx[1]
idx

tensor([[5, 4, 1],
        [6, 9, 4],
        [1, 3, 5],
        [0, 1, 9]])

In [14]:
label = torch.arange(10)+100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [15]:
torch.gather(label.expand(4, 10), dim=1, index=idx.long())

tensor([[105, 104, 101],
        [106, 109, 104],
        [101, 103, 105],
        [100, 101, 109]])