# Tensor advanced operation

In [1]:
import torch

## where

In [7]:
cond = torch.randn([2, 2])
cond

tensor([[ 1.2833,  1.0058],
        [-2.4641, -0.6243]])

In [8]:
a = torch.zeros([2, 2])
a

tensor([[0., 0.],
        [0., 0.]])

In [9]:
b = torch.ones([2, 2])
b

tensor([[1., 1.],
        [1., 1.]])

In [10]:
torch.where(cond>0.5, a, b)

tensor([[0., 0.],
        [1., 1.]])

## gather
收集