# Math operation

## basic

In [2]:
import torch

In [3]:
a = torch.rand(3, 4)

In [4]:
b = torch.rand(4)

In [5]:
a + b

tensor([[1.4403, 1.0049, 1.2656, 1.2903],
        [1.5087, 1.0631, 1.5117, 1.3500],
        [0.7348, 1.0678, 0.6932, 1.3969]])

In [6]:
torch.add(a, b)

tensor([[1.4403, 1.0049, 1.2656, 1.2903],
        [1.5087, 1.0631, 1.5117, 1.3500],
        [0.7348, 1.0678, 0.6932, 1.3969]])

In [7]:
torch.all(torch.eq(a-b, torch.sub(a,b)))

tensor(True)

In [8]:
torch.all(torch.eq(a*b, torch.mul(a,b)))

tensor(True)

In [9]:
torch.all(torch.eq(a/b, torch.div(a,b)))

tensor(True)

## matmul
矩阵相乘

In [12]:
a = 3 * torch.ones(2, 2)
a

tensor([[3., 3.],
        [3., 3.]])

In [13]:
b = torch.ones(2, 2)
b

tensor([[1., 1.],
        [1., 1.]])

In [14]:
torch.mm(a, b)

tensor([[6., 6.],
        [6., 6.]])

In [15]:
torch.matmul(a, b)

tensor([[6., 6.],
        [6., 6.]])

In [16]:
a@b

tensor([[6., 6.],
        [6., 6.]])

## Power

In [17]:
a = torch.full([2, 2], 3)

In [18]:
a.pow(2)

tensor([[9, 9],
        [9, 9]])

In [19]:
a**2

tensor([[9, 9],
        [9, 9]])

In [20]:
aa = a**2

In [21]:
# 倒数
aa.rsqrt()

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [22]:
aa**(0.5)

tensor([[3., 3.],
        [3., 3.]])

## Exp log

In [23]:
a = torch.exp(torch.ones(2, 2))

In [24]:
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [25]:
torch.log(a)

tensor([[1., 1.],
        [1., 1.]])

## Approximation
近似解

In [26]:
a = torch.tensor(3.14)

In [27]:
a.floor(), a.ceil(), a.trunc(), a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [28]:
a = torch.tensor(3.499)

In [29]:
a.round()

tensor(3.)

In [30]:
a = torch.tensor(3.5)

In [31]:
a.round()

tensor(4.)

## clamp
梯度裁剪

In [39]:
grad = torch.rand(2, 3)*15
grad

tensor([[12.2277,  7.0792,  5.8605],
        [ 2.9361,  2.9952, 14.3011]])

In [40]:
grad.max()

tensor(14.3011)

In [41]:
grad.median()

tensor(5.8605)

In [42]:
# 小于10的均为10
grad.clamp(10)

tensor([[12.2277, 10.0000, 10.0000],
        [10.0000, 10.0000, 14.3011]])

In [43]:
grad

tensor([[12.2277,  7.0792,  5.8605],
        [ 2.9361,  2.9952, 14.3011]])

In [44]:
# 0-10之间
grad.clamp(0, 10)

tensor([[10.0000,  7.0792,  5.8605],
        [ 2.9361,  2.9952, 10.0000]])