# indexing

In [2]:
import torch

In [3]:
a = torch.rand(4, 3, 28, 28)

In [4]:
a[0].shape

torch.Size([3, 28, 28])

In [5]:
a[0, 0].shape

torch.Size([28, 28])

In [6]:
a[0, 0, 2, 4]

tensor(0.3538)

# select first/last N

In [7]:
a.shape

torch.Size([4, 3, 28, 28])

In [8]:
a[:2].shape

torch.Size([2, 3, 28, 28])

In [9]:
a[:2, :1, :, :].shape

torch.Size([2, 1, 28, 28])

In [10]:
a[:2, 1:, :, :].shape

torch.Size([2, 2, 28, 28])

In [11]:
a[:2, -1:, :, :].shape

torch.Size([2, 1, 28, 28])

# select by steps

In [12]:
a[:, :, 0:28:2, 0:28:2].shape

torch.Size([4, 3, 14, 14])

In [13]:
a[:, :, ::2, ::2].shape

torch.Size([4, 3, 14, 14])

# select by specific index

In [14]:
a.shape

torch.Size([4, 3, 28, 28])

In [16]:
a.index_select(0, torch.tensor([0, 2])).shape

torch.Size([2, 3, 28, 28])

In [18]:
a.index_select(2, torch.arange(28)).shape

torch.Size([4, 3, 28, 28])

In [19]:
a.index_select(2, torch.arange(8)).shape

torch.Size([4, 3, 8, 28])

# ...

In [20]:
a.shape

torch.Size([4, 3, 28, 28])

In [21]:
a[...].shape

torch.Size([4, 3, 28, 28])

In [22]:
a[0, ...].shape

torch.Size([3, 28, 28])

In [23]:
a[:, 1, ...].shape

torch.Size([4, 28, 28])

In [24]:
a[..., :2].shape

torch.Size([4, 3, 28, 2])

# select by mask

In [28]:
x = torch.randn(3, 4)
x

tensor([[-0.3738, -0.3457, -1.5847, -0.5125],
        [-0.2037, -0.2725, -0.3784,  0.1897],
        [ 0.0587,  0.6788,  0.4937,  0.3948]])

In [29]:
mask = x.ge(0.5)
mask

tensor([[False, False, False, False],
        [False, False, False, False],
        [False,  True, False, False]])

In [31]:
torch.masked_select(x, mask)

tensor([0.6788])

In [32]:
torch.masked_select(x, mask).shape

torch.Size([1])

# select by flatten index

In [33]:
src = torch.tensor([[4, 3, 5],
                   [6, 7, 8]])

In [34]:
# 数据打平之后按索引取值
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])