# nn.module

In [2]:
from torch import nn

## nn.Module是所有网络层次的父类

- Linear
- ReLU
- Sigmoid
- Conv2d
- ConvTransposed2d
- Dropout
- etc

## container

In [ ]:
self.net = nn.Sequential(
    nn.Conv2d(1, 32, 5, 1, 1),
    nn.MaxPool2d(2, 2),
    nn.ReLU(True),
    nn.BatchNorm2d(32),

)

## parameters参数的有效管理

In [4]:
net = nn.Sequential(nn.Linear(4, 2), nn.Linear(2, 2))

In [5]:
list(net.parameters())[0].shape

torch.Size([2, 4])

In [6]:
list(net.parameters())[3].shape

torch.Size([2])

In [9]:
list(net.parameters())

[Parameter containing:
 tensor([[ 0.0395,  0.3533, -0.3600,  0.4204],
         [ 0.0567,  0.1942,  0.1561,  0.2454]], requires_grad=True),
 Parameter containing:
 tensor([-0.0101,  0.1221], requires_grad=True),
 Parameter containing:
 tensor([[0.2022, 0.6574],
         [0.1582, 0.3844]], requires_grad=True),
 Parameter containing:
 tensor([0.3975, 0.1698], requires_grad=True)]

In [10]:
# net.parameters()返回所有参数
# 没有名字的参数
# 有名字的参数
list(net.named_parameters())[0]

('0.weight',
 Parameter containing:
 tensor([[ 0.0395,  0.3533, -0.3600,  0.4204],
         [ 0.0567,  0.1942,  0.1561,  0.2454]], requires_grad=True))

In [11]:
list(net.named_parameters())[1]

('0.bias',
 Parameter containing:
 tensor([-0.0101,  0.1221], requires_grad=True))

In [12]:
dict(net.named_parameters()).items()

dict_items([('0.weight', Parameter containing:
tensor([[ 0.0395,  0.3533, -0.3600,  0.4204],
        [ 0.0567,  0.1942,  0.1561,  0.2454]], requires_grad=True)), ('0.bias', Parameter containing:
tensor([-0.0101,  0.1221], requires_grad=True)), ('1.weight', Parameter containing:
tensor([[0.2022, 0.6574],
        [0.1582, 0.3844]], requires_grad=True)), ('1.bias', Parameter containing:
tensor([0.3975, 0.1698], requires_grad=True))])

## to(device)

In [ ]:
device = torch.device('cuda')
net = Net()
net.to(device)

## save and load

In [ ]:
device = torch.device('cuda')
net = Net()
net.to(device)

# 判断是否有现有模型，如果有的话加载当前已有模型
net.load_state_dict(torch.load('ckpt.mdl'))

# train
# 保存当前已训练的模型
torch.save(net.state_dict(), 'ckpt.mdl')

## train/test
训练与测试切换

In [ ]:
device = torch.device('cuda')
net = Net()
net.to(device)

# train
net.train()


# test
net.eval()


## implement own layer
实现自己的类

In [ ]:
class Flatten(nn.Module):
    def __init__(self):
        super(Flatten, self).__init__()
        
    def forward(self, input):
        return input.view(input.size(0), -1)
    
class TestNet(nn.Module):
    def __init__(self):
        super(TestNet, self).__init__()
        self.net = nn.Sequential(nn.Conv2d(1, 16, stride=1, padding=1),
                                 nn.MaxPool2d(2, 2),
                                 Flatten(),
                                 nn.Linear(1*14*14, 10))
    
    def forward(self, x):
        return self.net(x)

## own linear layer
自己的线性层

In [ ]:
class MyLinear(nn.Module):
    def __init__(self, inp, outp):
        super(MyLinear, self).__init__()
        
        # requires_grad = True
        self.w = nn.Parameter(torch.randn(outp, inp))
        self.b = nn.Parameter(torch.randn(outp))
        
    def forward(self, x):
        x = x @ self.w.t() + self.b
        return x