# statistics

## norm
范数

In [2]:
import torch

In [12]:
a = torch.full([8], 1, dtype=torch.float)
a

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
b = a.view(2, 4)

In [15]:
c = a.view(2, 2, 2)

In [16]:
b

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
c

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [18]:
a.norm(1), b.norm(1), c.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [19]:
a.norm(2), b.norm(2), c.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284))

In [20]:
b.norm(1, dim=1)

tensor([4., 4.])

In [21]:
b.norm(2, dim=1)

tensor([2., 2.])

In [22]:
c.norm(1, dim=0)

tensor([[2., 2.],
        [2., 2.]])

In [23]:
c.norm(2, dim=0)

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])

## mean, sum, min, max, prod

In [25]:
a = torch.arange(8).view(2, 4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [26]:
# prod累乘
a.min(), a.max(), a.mean(), a.prod()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.))

In [27]:
a.sum()

tensor(28.)

In [29]:
# 最大值最小值索引，数据打平给出索引
a.argmax(), a.argmin()

(tensor(7), tensor(0))

In [30]:
# 每个维度上的最大值索引
a.argmax(dim=1)

tensor([3, 3])

## dim, keepdim

In [31]:
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [32]:
a.argmax(dim=1)

tensor([3, 3])

In [33]:
a.max(dim=1, keepdim=True)

torch.return_types.max(
values=tensor([[3.],
        [7.]]),
indices=tensor([[3],
        [3]]))

In [34]:
a.argmax(dim=1, keepdim=True)

tensor([[3],
        [3]])

## Top-k or k-th

In [43]:
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [35]:
a.topk(3, dim=1)

torch.return_types.topk(
values=tensor([[3., 2., 1.],
        [7., 6., 5.]]),
indices=tensor([[3, 2, 1],
        [3, 2, 1]]))

In [37]:
a.topk(3, dim=1, largest=False)

torch.return_types.topk(
values=tensor([[0., 1., 2.],
        [4., 5., 6.]]),
indices=tensor([[0, 1, 2],
        [0, 1, 2]]))

In [41]:
# 第3小
a.kthvalue(3, dim=1)

torch.return_types.kthvalue(
values=tensor([2., 6.]),
indices=tensor([2, 2]))

In [42]:
a.kthvalue(3)

torch.return_types.kthvalue(
values=tensor([2., 6.]),
indices=tensor([2, 2]))

## compare

In [44]:
# 大于
torch.gt(a, 0)

tensor([[False,  True,  True,  True],
        [ True,  True,  True,  True]])

In [45]:
torch.eq(a, a)

tensor([[True, True, True, True],
        [True, True, True, True]])

In [46]:
# 是否所有位置都相等
torch.equal(a, a)

True